defaults:
  - _self_
  - optimizer: adam
  - model: mlp
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  output_subdir: null
  run:
    dir: .

run:
  log:
    on: True
    wandb:
      on: True
      watch: False
      project: baselines
      entity: DanielPerezJensen
      offline: True
  plotting: False
  save: False

training:
  seeds: [42]
  gpu: 1
  epochs: 50
  batch_size: 256

data:
  scaler_name: none
  freq: M
  lagged_vars: [river_flow]
  lagged_stations: [34]
  target_var: river_flow
  target_stations: [34]
  time_features: True
  ndsi:
    index: False
    surface: False
    cloud: False
  ndvi:
    index: False
    surface: False
    cloud: False