defaults:
  - _self_
  - optimizer: adam
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  output_subdir: null
  run:
    dir: .

model:
  name: SeqGRU
  out_channels: 32
  num_layers: 1

run:
  log:
    on: True
    wandb:
      on: True
      watch: False
      project: baselines
      entity: DanielPerezJensen
      offline: True

training:
  gpu: 0
  epochs: 50
  batch_size: 256
  bias: True
  early_stopping: False
  patience: 5

data:
  scaler_name: none
  graph_type: base
  freq: W
  sequential: True
  lagged_vars: [river_flow]
  ndsi:
    index: False
    surface: False
    cloud: False
  ndvi:
    index: False
    surface: False
    cloud: False