defaults:
  - _self_
  - optimizer: adam
  - model: HeteroSeq
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  output_subdir: null
  run:
    dir: .

run:
  log:
    on: True
    wandb:
      on: True
      watch: False
      project: baselines
      entity: DanielPerezJensen
      offline: True
  save: False
  name: Base
  seeds: [42]

training:
  epochs: 50
  batch_size: 256
  gpu: 0

data:
  scaler_name: none
  graph_type: base
  freq: W
  sequential: True
  lagged_vars: [river_flow]
  time_features: False
  ndsi:
    index: False
    surface: False
    cloud: False
  ndvi:
    index: False
    surface: False
    cloud: False