name: gnn_env
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - pip=21.2.4
  - cudatoolkit=11.3.1
  - pytorch=1.11.0
  - pip:
    - jupyter==1.0.0
    - pandas==1.4.2
    - numpy==1.22.3
    - tqdm==4.64.0
    - scikit-learn==1.0.2
    - plotly==5.7.0
    - pytorch-lightning==1.6.3
    - wandb==0.12.16
    - hydroeval==0.1.0
    - networkx==2.8
    - pyvis==0.2.0
    - decorator==5.1.1
    - matplotlib==3.5.2
    - tensorboard==2.9.0
    - mypy==0.950
    - hydra-core==1.1.2
