defaults:
  - _self_
  - optimizer: adam
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  output_subdir: null
  run:
    dir: .

training:
  gpu: True
  epochs: 25
  batch_size: 16

data:
  scaler_name: none
  freq: W
  lag: 24
  lagged_variables: [river_flow, river_height]
  target_variable: river_flow
  target_stations: [0]