defaults:
  - _self_
  - optimizer: adam
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

hydra:
  output_subdir: null
  run:
    dir: .

model:
  out_channels: 32
  n_outputs: 1
  num_layers: 4

training:
  wandb:
    run: True
    watch: False
    project: graph
    entity: DanielPerezJensen
  gpu: 0
  epochs: 25
  batch_size: 128
  bias: True
  early_stopping: False
  patience: 5

data:
  scaler_name: none
  graph_type: base
  freq: W
  lag: 24
  lagged_variables: [river_flow, river_height]
  target_variable: river_flow
  target_stations: [0, 1, 2, 3]